// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Zemires.N8n.Api.Discover
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetIncludeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "schemas")]
        #pragma warning disable CS1591
        Schemas,
        #pragma warning restore CS1591
    }
}
