// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Zemires.N8n.Api.Models;
namespace Zemires.N8n.Api.DataTables.Item.Rows.Update
{
    /// <summary>
    /// Builds and executes requests for operations under \data-tables\{dataTableId}\rows\update
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-tables/{dataTableId}/rows/update", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpdateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-tables/{dataTableId}/rows/update", rawUrl)
        {
        }
        /// <summary>
        /// Update rows matching filter conditions in a data table.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse?> PatchAsUpdatePatchResponseAsync(global::Zemires.N8n.Api.Models.UpdateRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse> PatchAsUpdatePatchResponseAsync(global::Zemires.N8n.Api.Models.UpdateRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse>(requestInfo, global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update rows matching filter conditions in a data table.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PatchAsUpdatePatchResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse?> PatchAsync(global::Zemires.N8n.Api.Models.UpdateRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse> PatchAsync(global::Zemires.N8n.Api.Models.UpdateRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse>(requestInfo, global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update rows matching filter conditions in a data table.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Zemires.N8n.Api.Models.UpdateRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Zemires.N8n.Api.Models.UpdateRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdatePatchResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow>? DataTableRow { get; set; }
#nullable restore
#else
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow> DataTableRow { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdatePatchResponse();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else if(parseNode.GetCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow>(global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow.CreateFromDiscriminatorValue)?.AsList() is List<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow> dataTableRowValue)
                {
                    result.DataTableRow = dataTableRowValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else if(DataTableRow != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow>(null, DataTableRow);
                }
            }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow>? DataTableRow { get; set; }
#nullable restore
#else
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow> DataTableRow { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder.UpdateResponse();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else if(parseNode.GetCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow>(global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow.CreateFromDiscriminatorValue)?.AsList() is List<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow> dataTableRowValue)
                {
                    result.DataTableRow = dataTableRowValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else if(DataTableRow != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.Update.DataTableRow>(null, DataTableRow);
                }
            }
        }
    }
}
#pragma warning restore CS0618
