// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Zemires.N8n.Api.DataTables.Item.Rows.Delete;
using Zemires.N8n.Api.DataTables.Item.Rows.Update;
using Zemires.N8n.Api.DataTables.Item.Rows.Upsert;
using Zemires.N8n.Api.Models;
namespace Zemires.N8n.Api.DataTables.Item.Rows
{
    /// <summary>
    /// Builds and executes requests for operations under \data-tables\{dataTableId}\rows
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RowsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The deletePath property</summary>
        public global::Zemires.N8n.Api.DataTables.Item.Rows.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Zemires.N8n.Api.DataTables.Item.Rows.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder Update
        {
            get => new global::Zemires.N8n.Api.DataTables.Item.Rows.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upsert property</summary>
        public global::Zemires.N8n.Api.DataTables.Item.Rows.Upsert.UpsertRequestBuilder Upsert
        {
            get => new global::Zemires.N8n.Api.DataTables.Item.Rows.Upsert.UpsertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RowsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-tables/{dataTableId}/rows{?cursor*,filter*,limit*,search*,sortBy*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RowsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data-tables/{dataTableId}/rows{?cursor*,filter*,limit*,search*,sortBy*}", rawUrl)
        {
        }
        /// <summary>
        /// Query and retrieve rows from a data table with optional filtering, sorting, and pagination.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Models.DataTableRowList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.Models.DataTableRowList?> GetAsync(Action<RequestConfiguration<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.Models.DataTableRowList> GetAsync(Action<RequestConfiguration<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.Models.DataTableRowList>(requestInfo, global::Zemires.N8n.Api.Models.DataTableRowList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Insert one or more rows into a data table.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse?> PostAsRowsPostResponseAsync(global::Zemires.N8n.Api.Models.InsertRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse> PostAsRowsPostResponseAsync(global::Zemires.N8n.Api.Models.InsertRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse>(requestInfo, global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Insert one or more rows into a data table.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsRowsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse?> PostAsync(global::Zemires.N8n.Api.Models.InsertRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse> PostAsync(global::Zemires.N8n.Api.Models.InsertRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse>(requestInfo, global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Query and retrieve rows from a data table with optional filtering, sorting, and pagination.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Insert one or more rows into a data table.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Zemires.N8n.Api.Models.InsertRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Zemires.N8n.Api.Models.InsertRowsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1"/>, List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow&gt;, List&lt;int&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RowsPostResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow>? DataTableRow { get; set; }
#nullable restore
#else
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow> DataTableRow { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;int&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<int?>? Integer { get; set; }
#nullable restore
#else
            public List<int?> Integer { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1? RowsPostResponseMember1 { get; set; }
#nullable restore
#else
            public global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1 RowsPostResponseMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsPostResponse();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RowsPostResponseMember1 = new global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1();
                }
                else if(parseNode.GetCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow>(global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow.CreateFromDiscriminatorValue)?.AsList() is List<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow> dataTableRowValue)
                {
                    result.DataTableRow = dataTableRowValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<int?>()?.AsList() is List<int?> integerValue)
                {
                    result.Integer = integerValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RowsPostResponseMember1 != null)
                {
                    return RowsPostResponseMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(RowsPostResponseMember1 != null)
                {
                    writer.WriteObjectValue<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1>(null, RowsPostResponseMember1);
                }
                else if(DataTableRow != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow>(null, DataTableRow);
                }
                else if(Integer != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<int?>(null, Integer);
                }
            }
        }
        /// <summary>
        /// Query and retrieve rows from a data table with optional filtering, sorting, and pagination.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RowsRequestBuilderGetQueryParameters 
        {
            /// <summary>Paginate by setting the cursor parameter to the nextCursor attribute returned by the previous request&apos;s response. Default value fetches the first &quot;page&quot; of the collection. See pagination for more detail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>JSON string of filter conditions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>The maximum number of items to return.</summary>
            [QueryParameter("limit")]
            public double? Limit { get; set; }
            /// <summary>Search text across all string columns</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>Sort format: columnName:asc or columnName:desc</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortBy")]
            public string? SortBy { get; set; }
#nullable restore
#else
            [QueryParameter("sortBy")]
            public string SortBy { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RowsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RowsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1"/>, List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow&gt;, List&lt;int&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RowsResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow>? DataTableRow { get; set; }
#nullable restore
#else
            public List<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow> DataTableRow { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;int&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<int?>? Integer { get; set; }
#nullable restore
#else
            public List<int?> Integer { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1? RowsPostResponseMember1 { get; set; }
#nullable restore
#else
            public global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1 RowsPostResponseMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Zemires.N8n.Api.DataTables.Item.Rows.RowsRequestBuilder.RowsResponse();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RowsPostResponseMember1 = new global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1();
                }
                else if(parseNode.GetCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow>(global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow.CreateFromDiscriminatorValue)?.AsList() is List<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow> dataTableRowValue)
                {
                    result.DataTableRow = dataTableRowValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<int?>()?.AsList() is List<int?> integerValue)
                {
                    result.Integer = integerValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RowsPostResponseMember1 != null)
                {
                    return RowsPostResponseMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(RowsPostResponseMember1 != null)
                {
                    writer.WriteObjectValue<global::Zemires.N8n.Api.DataTables.Item.Rows.RowsPostResponseMember1>(null, RowsPostResponseMember1);
                }
                else if(DataTableRow != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Zemires.N8n.Api.DataTables.Item.Rows.DataTableRow>(null, DataTableRow);
                }
                else if(Integer != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<int?>(null, Integer);
                }
            }
        }
    }
}
#pragma warning restore CS0618
