// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Zemires.N8n.Api.Audit;
using Zemires.N8n.Api.CommunityPackages;
using Zemires.N8n.Api.Credentials;
using Zemires.N8n.Api.DataTables;
using Zemires.N8n.Api.Discover;
using Zemires.N8n.Api.Executions;
using Zemires.N8n.Api.Insights;
using Zemires.N8n.Api.Projects;
using Zemires.N8n.Api.SourceControl;
using Zemires.N8n.Api.Tags;
using Zemires.N8n.Api.Users;
using Zemires.N8n.Api.Variables;
using Zemires.N8n.Api.Workflows;
namespace Zemires.N8n.Api
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class N8nClient : BaseRequestBuilder
    {
        /// <summary>The audit property</summary>
        public global::Zemires.N8n.Api.Audit.AuditRequestBuilder Audit
        {
            get => new global::Zemires.N8n.Api.Audit.AuditRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The communityPackages property</summary>
        public global::Zemires.N8n.Api.CommunityPackages.CommunityPackagesRequestBuilder CommunityPackages
        {
            get => new global::Zemires.N8n.Api.CommunityPackages.CommunityPackagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credentials property</summary>
        public global::Zemires.N8n.Api.Credentials.CredentialsRequestBuilder Credentials
        {
            get => new global::Zemires.N8n.Api.Credentials.CredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dataTables property</summary>
        public global::Zemires.N8n.Api.DataTables.DataTablesRequestBuilder DataTables
        {
            get => new global::Zemires.N8n.Api.DataTables.DataTablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The discover property</summary>
        public global::Zemires.N8n.Api.Discover.DiscoverRequestBuilder Discover
        {
            get => new global::Zemires.N8n.Api.Discover.DiscoverRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The executions property</summary>
        public global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder Executions
        {
            get => new global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The insights property</summary>
        public global::Zemires.N8n.Api.Insights.InsightsRequestBuilder Insights
        {
            get => new global::Zemires.N8n.Api.Insights.InsightsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Zemires.N8n.Api.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Zemires.N8n.Api.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sourceControl property</summary>
        public global::Zemires.N8n.Api.SourceControl.SourceControlRequestBuilder SourceControl
        {
            get => new global::Zemires.N8n.Api.SourceControl.SourceControlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Zemires.N8n.Api.Tags.TagsRequestBuilder Tags
        {
            get => new global::Zemires.N8n.Api.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Zemires.N8n.Api.Users.UsersRequestBuilder Users
        {
            get => new global::Zemires.N8n.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The variables property</summary>
        public global::Zemires.N8n.Api.Variables.VariablesRequestBuilder Variables
        {
            get => new global::Zemires.N8n.Api.Variables.VariablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflows property</summary>
        public global::Zemires.N8n.Api.Workflows.WorkflowsRequestBuilder Workflows
        {
            get => new global::Zemires.N8n.Api.Workflows.WorkflowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.N8nClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public N8nClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "/api/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
