// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Zemires.N8n.Api.Executions.Item.Retry;
using Zemires.N8n.Api.Executions.Item.Stop;
using Zemires.N8n.Api.Executions.Item.Tags;
using Zemires.N8n.Api.Models;
namespace Zemires.N8n.Api.Executions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \executions\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecutionsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The retry property</summary>
        public global::Zemires.N8n.Api.Executions.Item.Retry.RetryRequestBuilder Retry
        {
            get => new global::Zemires.N8n.Api.Executions.Item.Retry.RetryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stop property</summary>
        public global::Zemires.N8n.Api.Executions.Item.Stop.StopRequestBuilder Stop
        {
            get => new global::Zemires.N8n.Api.Executions.Item.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Zemires.N8n.Api.Executions.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Zemires.N8n.Api.Executions.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/executions/{id}{?includeData*,redactExecutionData*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/executions/{id}{?includeData*,redactExecutionData*}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Models.Execution"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.Models.Execution?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.Models.Execution> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.Models.Execution>(requestInfo, global::Zemires.N8n.Api.Models.Execution.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Models.Execution"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.Models.Execution?> GetAsync(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder.ExecutionsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.Models.Execution> GetAsync(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder.ExecutionsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.Models.Execution>(requestInfo, global::Zemires.N8n.Api.Models.Execution.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieve an execution from your instance.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder.ExecutionsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder.ExecutionsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecutionsItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Retrieve an execution from your instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecutionsItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Whether or not to include the execution&apos;s detailed data.</summary>
            [QueryParameter("includeData")]
            public bool? IncludeData { get; set; }
            /// <summary>Controls execution data redaction. When `true`, execution output data is always redacted. When `false`, requests unredacted (revealed) data — requires the `execution:reveal` scope. When omitted, follows the workflow redaction policy.</summary>
            [QueryParameter("redactExecutionData")]
            public bool? RedactExecutionData { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecutionsItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder.ExecutionsItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
