// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Zemires.N8n.Api.Executions.Item;
using Zemires.N8n.Api.Executions.Stop;
using Zemires.N8n.Api.Models;
namespace Zemires.N8n.Api.Executions
{
    /// <summary>
    /// Builds and executes requests for operations under \executions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecutionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The stop property</summary>
        public global::Zemires.N8n.Api.Executions.Stop.StopRequestBuilder Stop
        {
            get => new global::Zemires.N8n.Api.Executions.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Zemires.N8n.Api.executions.item collection</summary>
        /// <param name="position">The ID of the execution.</param>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder"/></returns>
        public global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Zemires.N8n.Api.executions.item collection</summary>
        /// <param name="position">The ID of the execution.</param>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Zemires.N8n.Api.Executions.Item.ExecutionsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/executions{?cursor*,includeData*,limit*,projectId,redactExecutionData*,status*,workflowId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecutionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/executions{?cursor*,includeData*,limit*,projectId,redactExecutionData*,status*,workflowId*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve all executions from your instance.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Models.ExecutionList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Zemires.N8n.Api.Models.ExecutionList?> GetAsync(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Zemires.N8n.Api.Models.ExecutionList> GetAsync(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Zemires.N8n.Api.Models.ExecutionList>(requestInfo, global::Zemires.N8n.Api.Models.ExecutionList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all executions from your instance.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieve all executions from your instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecutionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Paginate by setting the cursor parameter to the nextCursor attribute returned by the previous request&apos;s response. Default value fetches the first &quot;page&quot; of the collection. See pagination for more detail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Whether or not to include the execution&apos;s detailed data.</summary>
            [QueryParameter("includeData")]
            public bool? IncludeData { get; set; }
            /// <summary>The maximum number of items to return.</summary>
            [QueryParameter("limit")]
            public double? Limit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("projectId")]
            public string? ProjectId { get; set; }
#nullable restore
#else
            [QueryParameter("projectId")]
            public string ProjectId { get; set; }
#endif
            /// <summary>Controls execution data redaction. When `true`, execution output data is always redacted. When `false`, requests unredacted (revealed) data — requires the `execution:reveal` scope. When omitted, follows the workflow redaction policy.</summary>
            [QueryParameter("redactExecutionData")]
            public bool? RedactExecutionData { get; set; }
            /// <summary>Status to filter the executions by.</summary>
            [Obsolete("This property is deprecated, use StatusAsGetStatusQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            /// <summary>Status to filter the executions by.</summary>
            [QueryParameter("status")]
            public global::Zemires.N8n.Api.Executions.GetStatusQueryParameterType? StatusAsGetStatusQueryParameterType { get; set; }
            /// <summary>Workflow to filter the executions by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workflowId")]
            public string? WorkflowId { get; set; }
#nullable restore
#else
            [QueryParameter("workflowId")]
            public string WorkflowId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ExecutionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Zemires.N8n.Api.Executions.ExecutionsRequestBuilder.ExecutionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
