// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Zemires.N8n.Api.Credentials.Schema.Item;
namespace Zemires.N8n.Api.Credentials.Schema
{
    /// <summary>
    /// Builds and executes requests for operations under \credentials\schema
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SchemaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Zemires.N8n.Api.credentials.schema.item collection</summary>
        /// <param name="position">The credential type name that you want to get the schema for</param>
        /// <returns>A <see cref="global::Zemires.N8n.Api.Credentials.Schema.Item.WithCredentialTypeNameItemRequestBuilder"/></returns>
        public global::Zemires.N8n.Api.Credentials.Schema.Item.WithCredentialTypeNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("credentialTypeName", position);
                return new global::Zemires.N8n.Api.Credentials.Schema.Item.WithCredentialTypeNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.Credentials.Schema.SchemaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchemaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credentials/schema", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Zemires.N8n.Api.Credentials.Schema.SchemaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SchemaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credentials/schema", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
